# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  LevelMaker_config = debug

else ifeq ($(config),release)
  LevelMaker_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := LevelMaker

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

LevelMaker:
ifneq (,$(LevelMaker_config))
	@echo "==== Building LevelMaker ($(LevelMaker_config)) ===="
	@${MAKE} --no-print-directory -C . -f LevelMaker.make config=$(LevelMaker_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f LevelMaker.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   LevelMaker"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"